"""add user level system

Revision ID: 05c0ce5237f1
Revises: f9251dbc66b0
Create Date: 2025-09-18 14:43:44.951821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '05c0ce5237f1'
down_revision = 'f9251dbc66b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_posts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_comments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_likes_received', sa.Integer(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'ENTREPRENEUR'"))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ENTREPRENEUR'"))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('total_likes_received')
        batch_op.drop_column('total_comments')
        batch_op.drop_column('total_posts')
        batch_op.drop_column('experience')
        batch_op.drop_column('level')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_type', sa.VARCHAR(length=20), server_default=sa.text("'ENTREPRENEUR'"), nullable=False),
    sa.Column('business_stage', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('interested_business_types', sqlite.JSON(), nullable=True),
    sa.Column('preferred_areas', sqlite.JSON(), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
